Changed validation (Syntax Check)

diff --git a/.github/workflows/properties_validation.yml b/.github/workflows/properties_validation.yml
--- a/.github/workflows/properties_validation.yml
+++ b/.github/workflows/properties_validation.yml
@@ -14,8 +14,10 @@ jobs:
 
       - name: Validate properties files
         run: |
-          sudo apt-get install -yq gettext
           for file in $(find . -name "*.properties"); do
-              echo "Validating $file"
-              msgfmt --check-format --check-domain -o /dev/null $file
+            echo "Validating $file"
+            if grep -qP '^[^=]*[^a-zA-Z0-9.].*=' $file; then
+              echo "Invalid syntax in $file"
+              exit 1
+            fi
           done
